# =========== #
# updater.yml #
# =========== #

# Define Name
name: Update From Upstream

# Description:
#   This actions workflow was designed to compile our image and upload it to
#   the Github Container Registry upon detecting an update in the upstream 
#   image.

#
# ===== [ Triggers ] ==========================================================
#

on:
  workflow_dispatch:
  schedule:
  - cron: '0 4 * * *'

#
# ===== [ Jobs ] ==============================================================
#

jobs:

  # 1.) Update Job
  updater:
    name: Image Updater Job
    runs-on: ubuntu-latest
    steps:

    # 1.1) Set up Workspace
    - name: Set up workspace
      uses: actions/checkout@v1

    # 1.2) Auth with GHCR
    - name: Authenticate with GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}

    # 1.3) Compare versions
    - name: Check if update available
      id: check
      uses: AzureSrv/docker-image-update-checker@main
      with:
        gh-user: ${{ secrets.GH_USERNAME }}
        gh-token: ${{ secrets.GH_TOKEN }}
        base-image: library/ghost:alpine
        image: ghcr.io/azuresrv/posts-ghost:latest
    
    # 1.4) Set up QEMU for arm64 compilation
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      if: steps.check.outputs.needs-updating == 'true'
    
    # 1.5) Set up Docker build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      if: steps.check.outputs.needs-updating == 'true'

    # 1.6) Build and Push
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/azuresrv/posts-ghost
        labels: latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
      if: steps.check.outputs.needs-updating == 'true'
